name: CI - Django Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: root
        ports: [ "3306:3306" ]
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt

      - name: Run Tests
        env:
          DB_HOST: 127.0.0.1
          DB_NAME: testdb
          DB_USER: user
          DB_PASSWORD: password
        run: |
          pytest --maxfail=1 --disable-warnings -q
      - name: Run Flake8 Lint
        run: |
          pip install flake8
          flake8 messaging_app --max-line-length=88

      - name: Run Coverage
        run: |
          pip install coverage
          coverage run -m pytest
          coverage xml
          coverage report
