apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app-blue   # Change to messaging-app-green when switching
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
